// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /me/ledger-entries"
  | "GET /me/notifications"
  | "GET /me/settlements"
  | "GET /me/settlements/{settlementId}"
  | "GET /me/transactions"
  | "GET /me/transactions/{transactionId}"
  | "POST /me/notifications/{notificationId}/acknowledge";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /me/ledger-entries": { kind: "scope", scope: "ledger:read" },
  "GET /me/notifications": { kind: "scope", scope: "notifications:read" },
  "GET /me/settlements": { kind: "scope", scope: "settlements:read" },
  "GET /me/settlements/{settlementId}": { kind: "scope", scope: "settlements:read" },
  "GET /me/transactions": { kind: "scope", scope: "collections:read" },
  "GET /me/transactions/{transactionId}": { kind: "scope", scope: "collections:read" },
  "POST /me/notifications/{notificationId}/acknowledge": { kind: "scope", scope: "notifications:acknowledge" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
