// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/url;

# ASSUMED interface — Flutterwave publishes its API as page-by-page reference documentation (developer.flutterwave.com), not a single downloadable OpenAPI document. Written to cover only what payment-collections-api calls: verifying a customer collection and disbursing/checking a merchant settlement payout (transfer). Uncertain: exact field-level validation rules, full error code catalogue, and whether transfer completion arrives synchronously or only via webhook — modeled here as a pollable status field.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.flutterwave.com/v3") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Verify a customer collection's status
    #
    # + headers - Headers to be sent with the request 
    # + return - Transaction status 
    resource isolated function get transactions/[string id]/verify(map<string|string[]> headers = {}) returns inline_response_200|error {
        string resourcePath = string `/transactions/${getEncodedUri(id)}/verify`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Disburse a merchant's net settlement payout
    #
    # + headers - Headers to be sent with the request 
    # + return - Transfer initiated 
    resource isolated function post transfers(TransferRequest payload, map<string|string[]> headers = {}) returns inline_response_200_1|error {
        string resourcePath = string `/transfers`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Check a settlement payout's status
    #
    # + headers - Headers to be sent with the request 
    # + return - Transfer status 
    resource isolated function get transfers/[string id](map<string|string[]> headers = {}) returns inline_response_200_1|error {
        string resourcePath = string `/transfers/${getEncodedUri(id)}`;
        return self.clientEp->get(resourcePath, headers);
    }
}

# Get Encoded URI for a given value.
#
# + value - Value to be encoded
# + return - Encoded string
isolated function getEncodedUri(anydata value) returns string {
    string|error encoded = url:encode(value.toString(), "UTF8");
    if encoded is string {
        return encoded;
    } else {
        return value.toString();
    }
}

public type Transaction record {
    int id?;
    string tx_ref?;
    string flw_ref?;
    decimal amount?;
    "KES"|"NGN" currency?;
    "successful"|"failed"|"pending" status?;
    # e.g. mobilemoney, card
    string payment_type?;
    string created_at?;
};

public type Transfer record {
    int id?;
    string reference?;
    decimal amount?;
    "KES"|"NGN" currency?;
    "NEW"|"PENDING"|"SUCCESSFUL"|"FAILED" status?;
    string created_at?;
};

public type inline_response_200_1 record {
    string status?;
    Transfer data?;
};

public type inline_response_200 record {
    string status?;
    Transaction data?;
};

public type TransferRequest record {
    # bank/mobile-money code
    string account_bank;
    string account_number;
    decimal amount;
    "KES"|"NGN" currency;
    # idempotency reference, e.g. our settlement id
    string reference;
    string narration?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
